# This is a basic workflow to help you get started with Actions
name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: requirements
        run: |
          npm install
      - name: git identity
        run: |
          git config user.email "adam.kariv@gmail.com"
          git config user.name "Adam Kariv"
      - name: deploy
        run: |
          git checkout main
          (git branch -D dist || true)
          git checkout -b dist
          rm .gitignore
          npm run prod
          cp dist/recognition/index.html dist/recognition/404.html
          (cp CNAME dist/recognition/ || true)
          git add dist/recognition
          git commit -m dist
          (git branch -D gh-pages || true)
          git subtree split --prefix dist/recognition -b gh-pages
          git push -f origin gh-pages:gh-pages
          git checkout main
          git branch -D gh-pages
          git branch -D dist
          git checkout .
          git push
